### ISSUE TITLE
Black screen after install

### ISSUE THREAD

**Issue by Ugwattu** [basecamp/omarchy#2434]
### System details

Intel i5 4590, nvidia gt630, omarchy 3.0.2

### What's wrong?

1. Fresh install of omarchy
2. After the initial restart I can't even login
3. All I see is black screen.

**Comment by vaqMAD** [comment]
How did you create your USB stick bootable ? Note that it's recommended to create it by using use [balenaEtcher](https://etcher.balena.io/) on Mac/Windows or [caligula](https://github.com/ifd3f/caligula) on Linux

I had similar problem when I installed Omarchy for a first time, I created bootable USB manually (using DD) - it didn't work.
Then I created it for a second time using balenaEtcher, and it worked. 


What kind of installation did you try ? From Omarchy iso ? 
You can also install it manually: https://learn.omacom.io/2/the-omarchy-manual/96/manual-installation

**Comment by mikevanl** [comment]
I had this issue. The problem was that I didn't disable secure boot.

**Comment by Ugwattu** [comment]
Secure Boot is disabled.
And I used balenaEcther to create bootable USB
ISO was official omarchy

**Comment by vaqMAD** [comment]
Have you tried manual installation?

**Comment by Ugwattu** [comment]
No I have not tried manual installation.

**Comment by vaqMAD** [comment]
Does Limine (boot loader) even load for you? 
It looks like this:

<img width="2832" height="1760" alt="Image" src="https://github.com/user-attachments/assets/0e75db38-732d-4096-bcb5-394c59129cd5" />

**Comment by Ugwattu** [comment]
Yes this does loads.

**Comment by Ugwattu** [comment]
Only till omarchy then Linux that's all

**Comment by Ugwattu** [comment]
![Image](https://github.com/user-attachments/assets/a2045515-fe03-46aa-abcd-f82c1ff188d8)

**Comment by Ugwattu** [comment]
![Image](https://github.com/user-attachments/assets/6cd0e2a3-8017-404a-844e-78508c7c12bc) it says configuration is valid at bottom left corner.

**Comment by vaqMAD** [comment]
Okay, so my guess is that the installer installed an instance of Arch on your computer but it's something wrong during the process and you didn't get clear error message.  As I said - I had similar problem.

_Perhaps some errors occurred during the installation, or some packages might not have been installed correctly due to an unstable internet connection or another issue, which is now causing this problem. There is something called [Omarchy Doctor](https://github.com/basecamp/omarchy/pull/2026) in plans - but but it hasn't been released yet_ 

It's pretty hard to spot errors during the installation because the messages and logs scroll by very quickly on the screen.
You can check whether the problem lies with UI -  Try pressing `Ctrl+Alt+F1 (through F6)` key after boot and see if terminal appears.

What can you do about it?
- You could try to manually debug what's wrong with the installation, but I wouldn't recommend it, it's complicated.
- Try creating a fresh ISO image on your USB stick and run the Omarchy installer again. This approach worked for me when I had a similar issue.
- Attempt a manual Arch installation -> users on [discord](https://discord.gg/X57gfb27) are helping with that.

**Comment by muhammedanasmithadi** [comment]
Intel i7 13th Gen, Nvidia RTX 3050

I've successfully installed Omarchy, but I can't boot into it. It usually freezes on the Acer screen. I've only reached the limine bootloader twice, and in both instances, the TTY failed to load. Tried manual installation. Same issue.

**Comment by Ugwattu** [comment]
Man this is frustrating i have tried manual install, tried v3.0.0, v3.0.1, v3.0.2 it gave the same issue, black screen, no terminal.

**Comment by vaqMAD** [comment]
> Man this is frustrating i have tried manual install, tried v3.0.0, v3.0.1, v3.0.2 it gave the same issue, black screen, no terminal.
And I assume that, you can't access terminal after manual installation ? 

@Ugwattu @ancxanas 
Can you guys share more information what does your hard drive configuration look like?

**Comment by ryanrhughes** [comment]
This sounds like a driver issue to me. I'm not sure what the solution would be exactly but looking into support for Nvidia GT630 is where I'd start. It may be necessary to boot to single user mode to get to a point where you can make the necessary changes to support this card.

Once identified, we can implement a proper fix.

**Comment by yapus** [comment]
The problem must be that latest nvidia-open-dkms 580 drivers fails to build with the recent Arch kernel 6.18
I had this issue when trying to update my omarchy installation and had to restore from snapshot to 6.17.x kernel and temporary add  `linux` and `linux-headers` to pacman `IgnorePkgs` option so it does not accidentally break again 

```
==> dkms install --no-depmod nvidia/580.105.08 -k 6.18.0-arch1-2-g14

Error! Bad return status for module build on kernel: 6.18.0-arch1-2-g14 (x86_64)
Consult /var/lib/dkms/nvidia/580.105.08/build/make.log for more information.
==> WARNING: `dkms install --no-de
```


Relevant error from /var/lib/dkms/nvidia/580.105.08/build/make.log:

```
nvidia-uvm/uvm_va_range_device_p2p.c: In function ‘alloc_device_p2p_mem’:                                     nvidia-uvm/uvm_va_range_device_p2p.c:363:13: error: too many arguments to function ‘get_dev_pagemap’; expected 1, have 2
  363 |             get_dev_pagemap(page_to_pfn(page), NULL);
      |             ^~~~~~~~~~~~~~~                                                                           In file included from /usr/lib/modules/6.18.0-arch1-2-g14/build/include/linux/mm.h:33,
                 from ././common/inc/nv-pgprot.h:30,
                 from ././common/inc/nv-linux.h:33,
                 from nvidia-uvm/uvm_linux.h:40,                                                                               from nvidia-uvm/uvm_common.h:43,
                 from nvidia-uvm/uvm_va_range_device_p2p.c:24:
/usr/lib/modules/6.18.0-arch1-2-g14/build/include/linux/memremap.h:214:21: note: declared here
  214 | struct dev_pagemap *get_dev_pagemap(unsigned long pfn);                                                     |                     ^~~~~~~~~~~~~~~
make[5]: *** [/usr/lib/modules/6.18.0-arch1-2-g14/build/scripts/Makefile.build:287: nvidia-uvm/uvm_va_range_device_p2p.o] Error 1
```
