### ISSUE TITLE
Touch Bar dead on T1 Macs: macbook12-spi-driver DKMS never builds

### ISSUE THREAD

**Issue by passerini** [basecamp/omarchy#10825]
### What happened

On a MacBookPro13,3 (2016 15", T1 chip), the Touch Bar is completely dead after
a fresh install. The row is dark and no function keys are available.

Three separate causes stack up, all in the Omarchy install path:

**1. `fix-spi-keyboard.sh` installs the DKMS package but not `linux-headers`.**

`install/hardware/apple/fix-spi-keyboard.sh` runs:

```
omarchy-pkg-add macbook12-spi-driver-dkms
```

`linux-headers` is not a dependency of that package, and nothing else in the
install pulls it in for this code path. (`install/hardware/fix-bcm43xx.sh` does
add `dkms linux-headers` alongside `broadcom-wl`, so the omission looks
accidental.) Without headers DKMS silently never builds:

```
$ dkms status
(empty)
$ ls /var/lib/dkms/
(empty)
```

The install prints no error, so the machine boots looking healthy. Keyboard and
trackpad still work because the kernel's own in-tree `applespi` covers them —
only the Touch Bar is missing, which makes this easy to misread as an
unsupported-hardware problem.

**2. With headers installed, `macbook12-spi-driver` does not compile on kernel 7.1.**

```
$ sudo pacman -S linux-headers
...
==> dkms install --no-depmod macbook12-spi-driver/0+git.315 -k 7.1.9-arch1-2
Error! Bad return status for module build on kernel: 7.1.9-arch1-2 (x86_64)
```

Five instances of kernel API drift since the driver's last update (2019):

| File | Error | Kernel change |
|---|---|---|
| `apple-ib-tb.c:1293` | `initialization of 'void (*)(struct platform_device *)' from incompatible pointer type 'int (*)(...)'` | `platform_driver.remove` returns `void` (6.11+) |
| `apple-ib-als.c:679` | same | same |
| `apple-ibridge.c:752` | `initialization of 'const __u8 *(*)(...)' from incompatible pointer type '__u8 *(*)(...)'` | `hid_driver.report_fixup` returns `const __u8 *` |
| `apple-ibridge.c:901` | `'struct acpi_driver' has no member named 'owner'` | `.owner` removed from `struct acpi_driver` |
| `applespi.c:64` | `fatal error: asm/unaligned.h: No such file or directory` | renamed to `linux/unaligned.h` (6.12+) |

The mainline drivers do not cover this hardware, so there is no fallback:
`hid-appletb-kbd`, `hid-appletb-bl` and `appletbdrm` all match only `05AC:8302`
/ `05AC:8102`, which are T2 Macs. The T1 iBridge is `05AC:8600`.

**3. Even once built, `apple-ibridge` loses a driver race against `hid-sensor-hub`.**

Both HID interfaces of the iBridge expose modalias
`hid:b0003g0003v000005ACp00008600`. `hid-sensor-hub` claims it with a generic
vendor/product match; `apple-ibridge` claims it via
`HID_USB_DEVICE(0x05AC, 0x8600)`. Both match, so whichever registers first wins
— and udev loads `hid-sensor-hub` from modalias as soon as USB enumerates,
well before `systemd-modules-load` gets to `apple-ibridge`:

```
kernel: hid-sensor-hub 0003:05AC:8600.0002: hiddev96,hidraw1: USB HID v1.01 Device [Apple Inc. iBridge]
kernel: apple_ibridge: loading out-of-tree module taints kernel
kernel: apple-ibridge-hid 0003:05AC:8600.0001: input,hidraw0: USB HID v1.01 Keyboard [Apple Inc. iBridge]
```

`apple-ibridge` recovers `.0001` from `hid-generic` but never gets `.0002`, and
the Touch Bar stays dark. Both platform devices bind and probe cleanly, so
nothing in the log suggests a failure.

### What was expected

A working Touch Bar on a Mac model that `fix-spi-keyboard.sh` explicitly
detects (`MacBookPro13,[123]` is in its regex).

### Steps to reproduce

1. Install Omarchy 4.0.2 on any T1 Mac (MacBookPro13,x or MacBookPro14,x).
2. Boot and look at the Touch Bar — dark.
3. `dkms status` → empty.

### Fix

All three parts were needed to get it working here:

1. Add `linux-headers` to the `omarchy-pkg-add` call in `fix-spi-keyboard.sh`.
2. Patch `macbook12-spi-driver` for the four API changes above. I excluded
   `applespi` from the DKMS build rather than fixing its one-line include, since
   the in-tree `applespi` is maintained, already works, and the DKMS copy would
   shadow it via `updates/dkms/` — the three iBridge modules don't reference it.
3. Ship a softdep so `apple-ibridge` registers first:

```
# /etc/modprobe.d/apple-ibridge.conf
softdep hid-sensor-hub pre: apple-ibridge
```

After all three, `apple-ibridge-hid` owns both `.0001` and `.0002` and the
Touch Bar works.

I'm happy to open a PR for items 1 and 3 if that's useful. Item 2 belongs in the
`macbook12-spi-driver-dkms` package rather than in the installer.

### System details

- Model: MacBookPro13,3 (Mac-A5C67F76ED83108C), Apple T1
- Omarchy: 4.0.2-1
- Kernel: 7.1.9-arch1-2
- CPU: Intel Skylake-H
- GPU: Intel HD Graphics 530 (i915) + AMD Radeon Pro 460 (amdgpu)
- iBridge: USB `05ac:8600`

**Comment by passerini** [comment]
### Correction: the softdep in point 3 is not sufficient

I proposed `softdep hid-sensor-hub pre: apple-ibridge` above. It installs
correctly — `modprobe --show-depends hid-sensor-hub` does list `apple-ibridge`
first — but it makes no difference at boot, and the Touch Bar was still dark
after a reboot.

The reason is that `hid-sensor-hub` is never `modprobe`d on this machine. It
gets pulled into the initramfs by mkinitcpio's `autodetect` (the iBridge is
present at build time), so it is already resident by the time USB enumerates.
A softdep only fires when modprobe is actually invoked, so it never runs:

```
kernel: hid-sensor-hub 0003:05AC:8600.0002: hiddev96,hidraw1: USB HID v1.01 Device [Apple Inc. iBridge]
kernel: apple_ibridge: loading out-of-tree module taints kernel.
kernel: apple-ibridge-hid 0003:05AC:8600.0001: input,hidraw0: USB HID v1.01 Keyboard [Apple Inc. iBridge]
```

The only way to win the race is to be in the initramfs too:

```
# /etc/mkinitcpio.conf.d/zz-apple-ibridge.conf
MODULES+=(apple-ibridge apple-ib-tb apple-ib-als)
```

**The filename matters, and this is a second bug.**
`install/hardware/apple/fix-spi-keyboard.sh` writes
`/etc/mkinitcpio.conf.d/macbook_spi_modules.conf` containing:

```
MODULES=(applespi intel_lpss_pci spi_pxa2xx_platform)
```

That is a plain `=`, not `+=`, so it *resets* the array rather than extending
it. mkinitcpio sources drop-ins in alphabetical order, so any drop-in sorting
before `macbook_spi_modules.conf` — the natural name `apple-ibridge.conf`
included — is silently discarded, with no warning in the build output. Hence
the `zz-` prefix.

This is exactly the hazard the comment inside Omarchy's own
`omarchy_hooks.conf` warns about:

> This reads MODULES midway through mkinitcpio's drop-in sourcing, so a
> later-sorting drop-in that resets MODULES outright — surface_device_modules.conf
> does — would strip nvidia_drm after kms was already dropped.

`macbook_spi_modules.conf` has the same defect as the `surface_device_modules.conf`
named there, and it should probably be `MODULES+=` as well. On a hybrid-graphics
Mac like this one the `kms` hook is kept regardless, so nothing broke here — but
it makes the file hostile to any other drop-in on every Mac it is written to.

So the corrected fix for point 3 is the initramfs preload, not the softdep.
With `linux-headers` installed, the driver patched, and that drop-in in place,
`apple-ibridge-hid` owns both `.0001` and `.0002` and the Touch Bar works.

**Comment by makoni** [comment]
Independent reproduction on a second model, a newer kernel, and one thing this issue does not yet cover.

**Same failure on MacBookPro14,3 / kernel 7.2.3-arch1-3 / Omarchy 4.0.3.** All four API errors are verbatim what you list, so the drift is not specific to 13,3 or to 7.1.x. I excluded `applespi` from the DKMS build for exactly the reason you give — the in-tree one already drives the keyboard and the DKMS copy would shadow it from `updates/dkms/` — so I never reached your fifth item (`asm/unaligned.h`). With the three iBridge modules patched, `dkms status` reports `installed` and the bar lights up.

**Confirming @passerini's `MODULES=` finding, with one detail.** `macbook_spi_modules.conf` is written with a plain `=` here too. On a default 14,3 install it happens to sort first, so nothing is being clobbered yet:

```
1  macbook_spi_modules.conf   MODULES=(applespi intel_lpss_pci spi_pxa2xx_platform)
2  omarchy_hooks.conf
3  omarchy_resume.conf
4  thunderbolt_module.conf    MODULES+=(thunderbolt)
```

The hazard is latent rather than active: `thunderbolt_module.conf` ships from `omarchy-settings` and uses `+=`, so it survives, but any drop-in that sorts before `m` would vanish silently. Worth fixing regardless, and it means "my Touch Bar works" reports can't be taken as evidence the bug is harmless.

**The part not covered here: the Touch Bar goes dark again after suspend/resume.** `apple-ib-tb` has no resume handler, and on resume the driver's idea of the panel state no longer matches the hardware. What is misleading is that everything still *looks* correct — both interfaces are still bound to `apple-ibridge-hid`, and `fnmode`, `idle_timeout` and `dim_timeout` all read back fine. Only the panel is dark. What I measured on this machine:

| attempt | result |
|---|---|
| write `fnmode` (same or different value) | no effect |
| `modprobe -r apple_ib_tb && modprobe apple_ib_tb` | no effect |
| reload the whole stack: `apple_ib_tb`, `apple_ib_als`, `apple_ibridge`, then load in boot order | relights |

Only the full reload re-runs `appletb_probe`, which resets `cur_tb_mode`/`cur_tb_disp` to `OFF` before calling `appletb_update_touchbar` — that reset appears to be what the hardware actually needs. One gotcha: unloading `apple_ibridge` releases `.0002` and `hid-sensor-hub` takes it straight back, so the rebind has to be repeated after the reload, not just before it. Driving this from `/usr/lib/systemd/system-sleep/` works; it needs to be dispatched asynchronously, since the reload takes about a second and `system-sleep` hooks block the resume completing.

This is a different driver stack from #7950, which rebinds the `1D6B:0301` virtual sub-device created by #7064's stack — `macbook12-spi-driver` doesn't create that device, so the two don't overlap.

Thanks for the write-up, and for the softdep correction — that matches what I saw: the softdep installs cleanly and changes nothing at boot.

**Comment by makoni** [comment]
Follow-up on item 2: the API drift is now patched upstream at marc-git/macbook12-spi-driver#3, against the `touchbar-driver-hid-driver` branch the AUR `macbook12-spi-driver-dkms` package builds from.

Five hunks, 14 insertions, 21 deletions — the four you list plus `no_llseek` → `noop_llseek`, which `applespi.c` also needs on 6.12+. Built against 7.2.3-arch1-3 with all four modules compiling; the three iBridge ones loaded and exercised on a MacBookPro14,3.

Two caveats worth knowing if anyone picks this up for packaging. The `applespi` hunks are build-tested only — I did not load that module, for the shadowing reason you give in item 2. And the `.remove` → `void` change does not build on kernels before 6.11, so if the package needs to keep working on older kernels those two hunks want version guards; I left them out rather than guess at the supported range.

That repository has not seen a commit since June 2024, so I would not count on it merging. If Omarchy ends up carrying a patched build, the diff is small enough to vendor directly.
